SET DEADLOCK_PRIORITY LOW
SET LOCK_TIMEOUT 20000

IF
    (
        NOT EXISTS (
            SELECT object_id
            FROM sys.objects
            WHERE object_id = OBJECT_ID(N'[dbo].[USHIPCOMMERCE_PARTNERS]') AND type = 'U'
            )
    )
    BEGIN

        CREATE TABLE dbo.USHIPCOMMERCE_PARTNERS (
            USERID VARCHAR(75),
            USERNAME VARCHAR(50),
            NAME VARCHAR(1000),
            PRIMARYCONTACTUSERNAME VARCHAR(200),
            ACTIVE NUMBER(1,0),
            AM VARCHAR(MAX),
            AM_NAME VARCHAR(1000),
            AE VARCHAR(),
            AE_NAME VARCHAR(121),
            STRATEGICPARTNER NUMBER(1,0),
            STARTDATE TIMESTAMP_NTZ(9),
            ENDDATE TIMESTAMP_NTZ(9),
            SHOPIFY NUMBER(1,0),
            PILOTSTARTDATE TIMESTAMP_NTZ(9),
            PILOTENDDATE TIMESTAMP_NTZ(9),
            CLOSEDATE TIMESTAMP_NTZ(9),
            STAGE VARCHAR(40),
            ACCOUNTNAME VARCHAR(1000),
            "StartDate(SkippedPilot)" TIMESTAMP_NTZ(9),
            SPMUSHIPEXPECTEDVOLUME FLOAT,
            USHIPEXPECTEDREVENUEANNUAL VARCHAR(100),
            ECOMMERCEPLATFORM VARCHAR(1000),
            MONTHLYRECURRINGREVENUE VARCHAR(100),
            SPMPILOTVOLUME FLOAT,
            USHIPEXPECTEDPILOTREVENUE VARCHAR(100),
            PILOTDURATIONMONTHS NUMBER(18,0),
            PILOTDURATIONDAYS NUMBER(9,0),
            MONTHLYUSHIPEXPECTEDPILOTREVENUE FLOAT,
            INVOICEDATE TIMESTAMP_NTZ(9),
            ANNUALFEE VARCHAR(100)
        )
    END
