name: ci-main

on:
  push:
    branches:
      - main

env:
  commit: ${{ github.sha }}

jobs:
  deploy:
    runs-on: [self-hosted, uship-linux]
    strategy:
      matrix:
        env: [dev]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Set up Flyway
      run: |
        curl -o /tmp/flyway.tar.gz https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.0.0/flyway-commandline-8.0.0-linux-x64.tar.gz
        tar -xzf /tmp/flyway.tar.gz -C /tmp
        sudo mv /tmp/flyway-8.0.0 /opt/flyway
        sudo ln -s /opt/flyway/flyway /usr/local/bin/flyway
    
    - name: Test Database Connection with Flyway Info
      env: 
        FLYWAY_URL: ${{secrets.DB_HOSTNAME}}
        FLYWAY_USER: ${{secrets.DB_USER}}
        FLYWAY_PASSWORD: ${{secrets.DB_PASS}}
      run: |
        sudo -E flyway info

  # rollback:
  #   runs-on: [self-hosted, uship-linux]

  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Rollback changes
  #     run: |
  #       # 