name: ci-main

on:
  push:
    branches:
      - main

env:
  commit: ${{ github.sha }}

jobs:
  deploy:
    runs-on: [self-hosted, uship-linux]
    strategy:
      matrix:
        env: [dev]

    steps:
    - uses: actions/checkout@v3

    # - name: Install Flyway | ${{matrix.env}}
    #   run: |
    #     ssh -i 
    #     wget -qO- https://download.red-gate.com/maven/release/org/flywaydb/enterprise/flyway-commandline/9.22.3/flyway-commandline-9.22.3-linux-x64.tar.gz | 
    #     tar -xvz && sudo ln -s `pwd`/flyway-9.22.3/flyway /usr/local/bin 

    - name: Test Database Connection
      run: |
        ping 10.95.195.203
        
      # flyway info -url=${{secrets.DB_URL}} -user=${{secrets.DB_USERNAME}} -password=${{secrets.DB_PASS}} 

  rollback:
    runs-on: [self-hosted, uship-linux]

    steps:
    - uses: actions/checkout@v3

    - name: Rollback changes
      run: |
        # 