name: ci-main

on:
  push:
    branches:
      - main
      - testing-connection

env:
  commit: ${{ github.sha }}

jobs:
  deploy:
    runs-on: [self-hosted, uship-linux]
    strategy:
      matrix:
        env: [dev]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Set up Flyway
      run: |
        curl -o /tmp/flyway.tar.gz https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.22.3/flyway-commandline-9.22.3-linux-x64.tar.gz
        tar -xzf /tmp/flyway.tar.gz -C /tmp
        sudo mv /tmp/flyway-9.22.3 /opt/flyway
        sudo ln -s /opt/flyway/flyway /usr/local/bin/flyway
        sudo apt-get install iputils-ping

    
    - name: Test Database Connection with Flyway Info
      env: 
        FLYWAY_URL: ${{secrets.DB_HOSTNAME}}
        FLYWAY_USER: ${{secrets.DB_USER}}
        FLYWAY_PASSWORD: ${{secrets.DB_PASS}}
        HOST: ${{secrets.HOSTNAME}}
      run: |
        ipconfig
        ping -w 10 $HOST

  # rollback:
  #   runs-on: [self-hosted, uship-linux]

  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Rollback changes
  #     run: |
  #       # 