name: ci-main

on:
  push:
    branches:
      - main

env:
  commit: ${{ github.sha }}

jobs:
  deploy:
    runs-on: [self-hosted, uship-linux]
    strategy:
      matrix:
        env: [dev]

    steps:
    - uses: actions/checkout@v3

    - name: Test Database Connection
      run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/20.04/prod.list)"
        sudo apt-get install mssql-tools
        lsb_release -a
        sqlcmd -S ${{secrets.DB_SERVER}} -U ${{secrets.DB_USER}} -P ${{secrets.DB_PASS}} -d ${{secrets.DB_NAME}} -Q "SELECT 1"

  # rollback:
  #   runs-on: [self-hosted, uship-linux]

  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Rollback changes
  #     run: |
  #       # 