name: Snowflake-SIG-ALLENV

on:
  workflow_dispatch:
  schedule:
    - cron: '0 07 * * *'

env:
  snowflake_username: ${{ secrets.SNOWFLAKE_USERNAME }}
  snowflake_keypassword: ${{ secrets.SNOWFLAKE_PVTKEY }}
  snowflake_password: ${{ secrets.SNOWFLAKE_PASSWORD }}
  snowflake_accountname: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  snowflake_database: ${{ secrets.SNOWFLAKE_DATABASE }}
  snowflake_warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
  snowflake_role: ${{ secrets.SNOWFLAKE_ROLE }}
  sig_config: ${{ secrets.SIG_CONFIG }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  deploy:
    runs-on: [self-hosted, uship-linux]
    environment:
      name: ${{ github.event.inputs.environment }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetches all history for all branches and tags

    - name: Set up Python 3.10.6
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.6

    - name: Install Requirements and Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f src/data_push/requirements.txt ]; then pip install -r src/data_push/requirements.txt; fi
        sudo dpkg --configure -a && true
        python src/extract_pyodbc.py | bash
        pip install pyodbc
      env:
        DISTRO: "Ubuntu"
        REMOVE_EXITS: 'true'
        DOCS_URL: "https://raw.githubusercontent.com/MicrosoftDocs/sql-docs/live/docs/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server.md"
        ODBC_VERSION: 18

    - name: Modify/Configure OpenSSL, ODBC connection String
      run: |
        sudo chmod +rwx /etc/ssl/openssl.cnf
        sudo sed -i 's/TLSv1.2/TLSv1/g' /etc/ssl/openssl.cnf
        sudo sed -i 's/SECLEVEL=2/SECLEVEL=0/g' /etc/ssl/openssl.cnf
        echo '[system_default_sect]\nMinProtocol = TLSv1.0\nCipherString = DEFAULT@SECLEVEL=0' | sudo tee -a /etc/ssl/openssl.cnf
    #     echo 'export CONNECTION_STRING="$CONNECTION_STRING TrustServerCertificate=yes"' >> $GITHUB_ENV
    #   env:
    #     CONNECTION_STRING: "Driver={ODBC Driver 18 for SQL Server};Server=${{ secrets.DB_SERVER }};Database=${{ secrets.DATABASE }};Uid=${{ secrets.DB_USER }};Pwd=${{ secrets.DB_PASS }};"

    - name: Upload data from Snowflake to DB
      id: data-upload
      run: python src/data_push/snowflake_sig_pipeline.py
    #   env:
    #     DB_SERVER: ${{ secrets.DB_SERVER }}
    #     DB_NAME: ${{ secrets.DATABASE }}
    #     USERNAME: ${{ secrets.DB_USER }}
    #     PASSWORD: ${{ secrets.DB_PASS }}

    # Alert in Slack
    # - name: Slack Notification
    #   uses: rtCamp/action-slack-notify@v2
    #   if: failure()
    #   env:
    #     SLACK_COLOR: ${{ job.status }}
    #     SLACK_WEBHOOK:  ${{ secrets.SLACK_WEBHOOK }}
    #     SLACK_TITLE: SNOWFLAKE-SIG-DATA-PUSH
    #     SLACK_MESSAGE: "A daily job of uploading to SIG from snowflake failed. Data Push Status for the environment: ${{ job.status }}"
