name: Python Script Workflow

# on: [push]
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment to deploy to (prod, dev, qa, sandbox)'
        options:
          - devPricing
          - dev
          - prod
          - qa
          - sandbox
        required: true
        default: 'devPricing'

jobs:
  deploy:
    runs-on: [self-hosted, uship-linux]
    environment:
      name: ${{ github.event.inputs.environment }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetches all history for all branches and tags
    - name: Set up Python 3.10.6
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python create_tables.py
      env:
        DB_SERVER: ${{ secrets.DB_SERVER }}
        DB_NAME: ${{ secrets.DB_NAME }}
        USERNAME: ${{ secrets.DB_USER }}
        PASSWORD: ${{ secrets.DB_PASS }}
