name: Python Script Workflow

# on: [push]
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment to deploy to (prod, dev, qa, sandbox)'
        options:
          - devPricing
          - prod
          - qa
          - sandbox
        required: true
        default: 'devPricing'

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetches all history for all branches and tags

    - name: Run Python script
      run: python create_tables.py
      env:
        DB_SERVER: ${{ secrets.JDBC_URL }}
        DB_NAME: ${{ secrets.DATABASE }}
        USERNAME: ${{ secrets.DB_USER }}
        PASSWORD: ${{ secrets.DB_PASS }}
