name: CI/CD Pipeline
on:
  workflow_dispatch: #[push, pull_request]

env:
  commit: ${{ github.sha }}
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  deploy_dev:
    name: Deploy / DEV
    uses: uShip/sql-db-migrations/.github/workflows/action.yml@main
    with:
      environment: 'dev'

  deploy_sand:
    name: Deploy / Staging
    needs: deploy_dev
    uses: uShip/sql-db-migrations/.github/workflows/action.yml@main
    with:
      environment: 'sandbox'

  deploy_qa:
    name: Deploy / Review
    needs: deploy_dev
    uses: uShip/sql-db-migrations/.github/workflows/action.yml@main
    with:
      environment: 'qa'

  deploy_production:
      name: Deploy / Production
      needs: [deploy_sand, deploy_qa]
      uses: uShip/sql-db-migrations/.github/workflows/action.yml@main
      with:
        environment: 'prod'
