name: CI/CD Pipeline

on:
  workflow_dispatch: # To manually trigger the workflow
  # push: # Automatically trigger on push
  #   branches:
  #     - main
  # pull_request: # Automatically trigger on pull request

env:
  commit: ${{ github.sha }}

jobs:
  deploy_dev:
    name: Deploy / DEV
    uses: uShip/sql-db-migrations/.github/workflows/action.yml@main
    with:
      environment: 'dev'
    secrets:
      DB_SERVER: ${{ secrets.DEV_DB_SERVER }}
      DATABASE: ${{ secrets.DEV_DATABASE }}
      USERNAME: ${{ secrets.DEV_DB_USER }}
      PASSWORD: ${{ secrets.DEV_DB_PASS }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy_sand:
    name: Deploy / SANDBOX
    needs: deploy_dev
    uses: uShip/sql-db-migrations/.github/workflows/action.yml@main
    with:
      environment: 'sandbox'
    secrets:
      DB_SERVER: ${{ secrets.SAND_DB_SERVER }}
      DATABASE: ${{ secrets.SAND_DATABASE }}
      USERNAME: ${{ secrets.SAND_DB_USER }}
      PASSWORD: ${{ secrets.SAND_DB_PASS }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy_qa:
    name: Deploy / QA
    needs: deploy_dev
    uses: uShip/sql-db-migrations/.github/workflows/action.yml@main
    with:
      environment: 'qa'
    secrets:
      DB_SERVER: ${{ secrets.QA_DB_SERVER }}
      DATABASE: ${{ secrets.QA_DATABASE }}
      USERNAME: ${{ secrets.QA_DB_USER }}
      PASSWORD: ${{ secrets.QA_DB_PASS }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy_production:
      name: Deploy / Production
      needs: [deploy_sand, deploy_qa]
      uses: uShip/sql-db-migrations/.github/workflows/action.yml@main
      with:
        environment: 'prod'
      secrets:
        DB_SERVER: ${{ secrets.PROD_DB_SERVER }}
        DATABASE: ${{ secrets.PROD_DATABASE }}
        USERNAME: ${{ secrets.PROD_DB_USER }}
        PASSWORD: ${{ secrets.PROD_DB_PASS }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
