name: db-workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (prod, dev, qa, sandbox)'
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: [self-hosted, uship-linux]
    environment: 
      name: ${{ github.event.inputs.environment }}
    steps:
    - name: Validate environment
      run: |
        echo "Selected environment: ${{ github.event.inputs.environment }}"
        case "${{ github.event.inputs.environment }}" in prod|dev|qa|sandbox) 
            echo "Deploying to ${{ github.event.inputs.environment }}"
            ;;*)
            echo "Error: Invalid environment selected. Allowed values are prod, dev, qa, or sandbox"
            exit 1
            ;;
        esac

    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18
    
    - name: Installing Goose
      run: |
        go install github.com/pressly/goose/v3/cmd/goose@latest
        goose --version