name: db-workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (prod, dev, qa, sandbox)'
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: [self-hosted, uship-linux]
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install SQLFluff
      run: |
        pip install sqlfluff

    - name: Fix SQL files
      run: |
        sqlfluff fix --dialect tsql . --exclude-rules RF04,LF05

    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code || echo "::set-output name=changes::true"

    - name: Commit and push if changes
      run: |
        git add -A
        git commit -m "Auto-fix SQL files" -a || echo "No changes to commit"
        git push


    - name: Validate environment
      run: |
        echo "Selected environment: ${{ github.event.inputs.environment }}"
        case "${{ github.event.inputs.environment }}" in prod|dev|qa|sandbox|devPricing)
            echo "Deploying to ${{ github.event.inputs.environment }}"
            ;;*)
            echo "Error: Invalid environment selected. Allowed values are prod, dev, qa, or sandbox"
            exit 1
            ;;
        esac

    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'

    - name: Set up Flyway
      run: |
        curl -o /tmp/flyway.tar.gz https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.22.3/flyway-commandline-9.22.3-linux-x64.tar.gz
        tar -xzf /tmp/flyway.tar.gz -C /tmp
        sudo mv /tmp/flyway-9.22.3 /opt/flyway
        sudo ln -s /opt/flyway/flyway /usr/local/bin/flyway

    - name: Test Database Connection with Flyway Info
      env:
        FLYWAY_URL: ${{ secrets.JDBC_URL }}
        FLYWAY_USER: ${{ secrets.DB_USER }}
        FLYWAY_PASSWORD: ${{ secrets.DB_PASS }}
      run: |
        sudo -E flyway migrate
